name: flutter_bluetooth_printer
description: Image based printing for bluetooth thermal printer, support for iOS and Android.
version: 2.17.18
repository: https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin

false_secrets:
  - example/**

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  plugin_platform_interface: ^2.1.8
  flutter:
    sdk: flutter

  image: ">=4.1.7"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: id.flutter.plugins
        pluginClass: FlutterBluetoothPrinterPlugin
        dartPluginClass: MethodChannelBluetoothPrinter

  fonts:
    - family: Receipt
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 600
